name: Checks

on:
  pull_request:
    branches: [main]

jobs:
  test-lint:
    name: Test and Lint
    uses: ./.github/workflows/test-and-lint.yml
    secrets:
      DOCKERHUB_USER: ${{ vars.DOCKER_HUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
