name: Deploy

on:
  push:
    branches:
     -main
     -prod

jobs:
  test-lint:
    uses:
    name: Test and Lint
    secrets:
      DOCKERHUB_USER: ${{vars.DOCKER_HUB_USER}}
      DOCKERHUB_TOKEN: ${{secrets.DOCKER_HUB_TOKEN}}

  deploy:
    name: Deploy
    runs: ubuntu-22.04
    needs: [test-lint]
    steps:
      - name: Checkout
        uses: action/checkout@v4
      - name: Set vars
        run:  |
          if  [[ $GITHUB_REF == 'refs/heads/prod' ]]; then
            ehco "prod" > .workspace
          else
            echo "staging" > .workspace
          fi
      - name: Push to ECR
        env:
          AWS_ACCESS_KEY_ID: ${{vars.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{vars.AWS_SECRET_ACCESS_KEY}}
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{vars.AWS_ACCOUNT_ID}}.dkr.ecr.eu-noth-1.amazonaws.com
          docker build --compress -t ${{vars.ECR_REPO_APP}}:$GITHUB_SHA .
          docker push ${{vars.ECR_REPO_APP}}:$GITHUB_SHA .
          docker build --compress -t ${{vars.ECR_REPO_PROXY}}:$GITHUB_SHA proxy/
          docker push ${{vars.ECR_REPO_PROXY}}:$GITHUB_SHA
