name: Destroy

on:
  workflow_dispatch:
    inputs:
      envrionment:
        type: choice
        description: Whcih envrionment to remove AWS resources for?
        options:
          - staging
          - prod

jobs:
 destroy:
  name: Destroy
  runs-on: ubuntu-22.04
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Terraform Destroy
      env:
        AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        exprot TF_WORKSPACE=${{ github.event.inputs.envrionment }}
        cd infra/
        docker compose run --rm terrafrom -chdir=deploy/ init
        decker compose run --rm terrrafrom -chdir=deploy/ destroy -auto-approve

